---
- hosts: exoscale
  remote_user: root
  vars:
    password: unPbyhGuoKiAc
  tasks:
    - name: Crea usuario
      user: name=bot shell=/bin/bash groups=users,sudo append=yes password={{password}}
    - name: Instala supervisor
      apt: name=supervisor state=present
    - name: Configura supervisor
      copy: src=supervisord.conf dest=/etc/supervisor/supervisord.conf 
    - name: Configura supervisor
      copy: src=gobot.conf dest=/etc/supervisor/conf.d/gobot.conf 
    - name: Ejecuta supervisor
      service: name=supervisor state=started
    - name: Descarga aplicación
      become: yes
      become_user: bot
      git: repo=http://github.com/JJ/CuantoQuedaBot dest=/home/bot/CuantoQuedaBot